<?php
/**
 * Created by PhpStorm.
 * User: julkwel
 * Date: 3/10/19
 * Time: 8:43 PM
 */

namespace App\Shared\Form;


use App\Shared\Entity\SkClasse;
use App\Shared\Entity\SkNiveau;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClasseFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('classeNom',TextType::class)
                ->add('niveau',EntityType::class,array('class'=>SkNiveau::class))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array('data_class'=>SkClasse::class));
    }

    public function getBlockPrefix()
    {
        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }
}